In [8]:
import pandas as pd
import numpy as np

In [9]:
city_fac_bloomington = pd.read_csv('City_Facilities.csv')

city_fac_bloomington

Place ID                              Facility    Facility Group  \
0        1561                     Ferguson Dog Park             Parks   
1        5069                        Innovation Lab      City Offices   
2        1795                         Latimer Woods             Parks   
3        5044  Frank Southern Ice Arena Parking Lot  Parking Facility   
4          95             Banneker Community Center             Parks   
..        ...                                   ...               ...   
174      3314                 Seminary Square Plaza             Parks   
175      1792                  Building Trades Park             Parks   
176      5043                  Carlisle Parking Lot  Parking Facility   
177       873                            Mills Pool             Parks   
178      4968       Switchyard Park Rogers Entrance             Parks   

                     Type  Address Location ID  \
0                Dog Park              59053.0   
1      Government Offices               4995.0   
2    Nature Park/Preserve              50536.0   
3                 Parking                  NaN   
4        Community Center               4159.0   
..                    ...                  ...   
174       Park Plaza Area                  NaN   
175     Neighborhood Park              14385.0   
176               Parking                  NaN   
177         Swimming Pool              15132.0   
178              Entrance                  NaN   

                                              Location  X Coordinate  \
0                                 4300 N Stone Mill RD       3108927   
1                                      627 N Morton ST       3107860   
2                           3200 E Buick Cadillac BLVD       3120156   
3                        N of Frank Southern Ice Arena       3110466   
4                                         930 W 7th ST       3105365   
..                                                 ...           ...   
174  West side of the W 2nd ST Kroger Grocery Store...       3107895   
175                                      619 W Howe ST       3106615   
176     Title 15 Lot 23, commonly know as Carlisle Lot       3111812   
177                                     1100 W 14th ST       3105426   
178                                                NaN       3107183   

     Y Coordinate   Latitude  Longitude  \
0         1443195  39.209444 -86.532102   
1         1429780  39.172582 -86.536221   
2         1424789  39.158671 -86.492991   
3         1419288  39.143733 -86.527257   
4         1428432  39.168922 -86.545049   
..            ...        ...        ...   
174       1425268  39.160194 -86.536193   
175       1426014  39.162269 -86.540628   
176       1422589  39.152773 -86.522438   
177       1431028  39.176049 -86.544780   
178       1420723  39.147728 -86.538800   

                                     Geometry  
0    POINT (-86.532174816526 39.209402001487)  
1    POINT (-86.536225864906 39.172589612604)  
2    POINT (-86.492971346064 39.158675449588)  
3    POINT (-86.527261036202 39.143740768385)  
4    POINT (-86.545054219197 39.168929719659)  
..                                        ...  
174   POINT (-86.536198398859 39.16020153292)  
175  POINT (-86.540696571373 39.162270752037)  
176  POINT (-86.522443568047 39.152780789759)  
177  POINT (-86.544784713551 39.176055933572)  
178  POINT (-86.538805184572 39.147735422084)  

[179 rows x 11 columns]

In [10]:
city_fac_bloomington.isnull().sum()

Place ID                0
Facility                0
Facility Group          0
Type                    0
Address Location ID    75
Location               14
X Coordinate            0
Y Coordinate            0
Latitude                0
Longitude               0
Geometry                0
dtype: int64

In [11]:
# Drop a single column
city_fac_bloomington = city_fac_bloomington.drop(columns=["Address Location ID"])

In [12]:
city_fac_bloomington

Place ID                              Facility    Facility Group  \
0        1561                     Ferguson Dog Park             Parks   
1        5069                        Innovation Lab      City Offices   
2        1795                         Latimer Woods             Parks   
3        5044  Frank Southern Ice Arena Parking Lot  Parking Facility   
4          95             Banneker Community Center             Parks   
..        ...                                   ...               ...   
174      3314                 Seminary Square Plaza             Parks   
175      1792                  Building Trades Park             Parks   
176      5043                  Carlisle Parking Lot  Parking Facility   
177       873                            Mills Pool             Parks   
178      4968       Switchyard Park Rogers Entrance             Parks   

                     Type                                           Location  \
0                Dog Park                               4300 N Stone Mill RD   
1      Government Offices                                    627 N Morton ST   
2    Nature Park/Preserve                         3200 E Buick Cadillac BLVD   
3                 Parking                      N of Frank Southern Ice Arena   
4        Community Center                                       930 W 7th ST   
..                    ...                                                ...   
174       Park Plaza Area  West side of the W 2nd ST Kroger Grocery Store...   
175     Neighborhood Park                                      619 W Howe ST   
176               Parking     Title 15 Lot 23, commonly know as Carlisle Lot   
177         Swimming Pool                                     1100 W 14th ST   
178              Entrance                                                NaN   

     X Coordinate  Y Coordinate   Latitude  Longitude  \
0         3108927       1443195  39.209444 -86.532102   
1         3107860       1429780  39.172582 -86.536221   
2         3120156       1424789  39.158671 -86.492991   
3         3110466       1419288  39.143733 -86.527257   
4         3105365       1428432  39.168922 -86.545049   
..            ...           ...        ...        ...   
174       3107895       1425268  39.160194 -86.536193   
175       3106615       1426014  39.162269 -86.540628   
176       3111812       1422589  39.152773 -86.522438   
177       3105426       1431028  39.176049 -86.544780   
178       3107183       1420723  39.147728 -86.538800   

                                     Geometry  
0    POINT (-86.532174816526 39.209402001487)  
1    POINT (-86.536225864906 39.172589612604)  
2    POINT (-86.492971346064 39.158675449588)  
3    POINT (-86.527261036202 39.143740768385)  
4    POINT (-86.545054219197 39.168929719659)  
..                                        ...  
174   POINT (-86.536198398859 39.16020153292)  
175  POINT (-86.540696571373 39.162270752037)  
176  POINT (-86.522443568047 39.152780789759)  
177  POINT (-86.544784713551 39.176055933572)  
178  POINT (-86.538805184572 39.147735422084)  

[179 rows x 10 columns]

In [13]:
# Display rows with missing values
missing_rows = city_fac_bloomington[city_fac_bloomington.isnull().any(axis=1)]
print("📌 Rows with Missing Values:")
print(missing_rows)

📌 Rows with Missing Values:
     Place ID                               Facility    Facility Group  \
7        4895            Upper Cascades Park Shelter             Parks   
42       4887   Lower Cascades Park Sycamore Shelter             Parks   
49       4892           RCA Community Park Shelter 2             Parks   
50       4852    Clear Creek Trail Parking Lot South  Parking Facility   
60       4891           RCA Community Park Shelter 1             Parks   
71       5041          Ferguson Dog Park Parking Lot  Parking Facility   
74       4967        Switchyard Park Walnut Entrance             Parks   
95       4853     Bloomington Rail Trail Parking Lot  Parking Facility   
105      4851    Clear Creek Trail Parking Lot North  Parking Facility   
136      4886  Lower Cascades Park Waterfall Shelter             Parks   
151      4897        Upper Cascades Park Parking Lot  Parking Facility   
153      4890                    Olcott Park Shelter             Parks   
167      4

In [14]:
import pandas as pd

# Manually added missing values for 'Location'
updated_locations = {
    "Switchyard Park Rogers Entrance": "1601 S Rogers St, Bloomington, IN 47403",
    "Upper Cascades Park Shelter": "514 W Club House Dr, Bloomington, IN 47404",
    "Lower Cascades Park Sycamore Shelter": "013-29010, E 10th St, Bloomington, IN 47404",
    "RCA Community Park Shelter 2": "1400 W Rca Park Dr, Bloomington, IN 47403",
    "Clear Creek Trail Parking Lot South": "Clear Creek Trail, Bloomington, IN 47403",
    "RCA Community Park Shelter 1": "1400 W Rca Park Dr, Bloomington, IN 47403",
    "Ferguson Dog Park Parking Lot": "4300 N Stone Mill Rd, Bloomington, IN 47408",
    "Switchyard Park Walnut Entrance": "1836 S Walnut St, Bloomington, IN 47401",
    "Bloomington Rail Trail Parking Lot": "298 W Country Club Dr, Bloomington, IN 47403",
    "Clear Creek Trail Parking Lot North": "Clear Creek Trail, Bloomington, IN 47403",
    "Lower Cascades Park Waterfall Shelter": "2851 N Old State Road 37, Bloomington, IN 47408",
    "Upper Cascades Park Parking Lot": "514 W Club House Dr, Bloomington, IN 47404",
    "Olcott Park Shelter": "401 N. Morton St. Ste. 250, Bloomington, IN 47408",
    "Clear Creek Trail Parking Lot Central": "1498 W That Rd, Bloomington, IN 47403",
}

# Update the 'Location' column based on facility names
city_fac_bloomington["Location"] = city_fac_bloomington.apply(
    lambda row: updated_locations.get(row["Facility"], row["Location"]), axis=1
)

In [15]:
# Display rows with missing values
missing_rows = city_fac_bloomington[city_fac_bloomington.isnull().any(axis=1)]
print("📌 Rows with Missing Values:")
print(missing_rows)

📌 Rows with Missing Values:
Empty DataFrame
Columns: [Place ID, Facility, Facility Group, Type, Location, X Coordinate, Y Coordinate, Latitude, Longitude, Geometry]
Index: []


In [16]:
# Get unique values from a specific column (e.g., "Facility Group")
unique_values_loc = city_fac_bloomington["Location"].dropna().unique()

# Print the unique values
print("📌 Unique values in 'Location':")
print(unique_values_loc)

📌 Unique values in 'Location':
['4300 N Stone Mill RD' '627 N Morton ST' '3200 E Buick Cadillac BLVD'
 'N of Frank Southern Ice Arena' '930 W 7th ST' '930 W 4th ST'
 'S College AVE south of Convention Center'
 '514 W Club House Dr, Bloomington, IN 47404' '3550 N Kinser PIKE'
 '2602 N Kinser PIKE' '2300 E Canada DR' '2350 W Bloomfield RD'
 '3010 E Daniel ST' '401 N Morton ST' '4421 E Morningside DR'
 '1400 W RCA Park DR' '2100 S Henderson ST'
 'W side of Headley Road, South of Griffy Lake' '810 N Woodlawn AVE'
 '3190 S Walnut ST' 'Runs from Sherwood Oaks Park to Childs School'
 '2120 S Highland AVE' 'Across from the Monroe County Public Library'
 '401 N Morton ST STE 150' '2201 E 3rd ST' '1100 W 4th ST'
 'Along the B-Trail from Grimes LN to Country Club DR'
 'Eastern edge of Griffy Lake shoreline' '600 E Miller DR'
 '1001 S Henderson ST' '1987 S Henderson ST' '514 W Club House DR'
 'Showers City Hall South Parking Lot' '3421 E Longview AVE'
 'Near Lanam RD' '1209 W 15th ST' 'Griffy Lake

In [ ]:
import pandas as pd
import re

# Standardizing street type abbreviations
street_abbreviations = {
    " ST": " Street",
    " RD": " Road",
    " AVE": " Avenue",
    " BLVD": " Boulevard",
    " DR": " Drive",
    " LN": " Lane",
    " PIKE": " Pike",
    " PKWY": " Parkway",
    " CIR": " Circle",
    " CT": " Court",
    " HWY": " Highway"
}

# Function to clean and standardize addresses
def standardize_address(location):
    if pd.isna(location):  # Handle missing values
        return location

    # Ensure location is a string
    location = str(location).strip().title()

    # Replace common abbreviations with full names
    for abbr, full in street_abbreviations.items():
        location = re.sub(rf"{abbr}\b", full, location, flags=re.IGNORECASE)

    # Ensure consistent formatting with Bloomington, IN and zip code
    if "Bloomington" not in location:
        location += ", Bloomington, IN"

    return location

# Apply function to standardize Location column
city_fac_bloomington["Location"] = city_fac_bloomington["Location"].apply(standardize_address)

# Save the cleaned dataset
upd_city_fac_bloomington.to_csv("city_fac_bloomington_standardized.csv", index=False)

# Display a preview of updated locations
print(upd_city_fac_bloomington[["Facility", "Location"]].head(20))

In [ ]:
upd_city_fac_bloomington

## Hospitals

Place ID,Facility,Facility Group,Type,Location,X Coordinate,Y Coordinate,Latitude,Longitude,Geometry
, IU Health Bloomington Hospital,Healthcare,Hospital,"2651 E Discovery Parkway, Bloomington, IN 47408",,,,
, Brickyard Healthcare - Bloomington Care Center,Healthcare,Nursing Home,"155 E Burks Drive, Bloomington, IN 47401",,,,
, Bloomington Regional Rehabilitation Hospital,Healthcare,Specialized Hospital,"3050 N Lintel Drive, Bloomington, IN 47404",,,,
, Hearthstone Health Campus,Healthcare,Assisted Living Facility,"3043 N Lintel Drive, Bloomington, IN 47404",,,,
, Majestic Care of Bloomington,Healthcare,Nursing Home,"1100 S Curry Pike, Bloomington, IN 47403",,,,
, Indiana University Student Health Center,Healthcare,Medical Center,"600 N Eagleson Avenue, Bloomington, IN 47405",,,,
, Bloomington Meadows Hospital,Healthcare,Mental Health Clinic,"3600 N Prow Road, Bloomington, IN 47404",,,,
, Stonecroft Health Campus,Healthcare,Assisted Living Facility,"363 S Fieldstone Boulevard, Bloomington, IN 47403",,,,
, HealthNet Bloomington Health Center,Healthcare,Medical Clinic,"811 W 2nd Street, Bloomington, IN 47403",,,,
, Bloomington Hospital Home Health,Healthcare,Home Health Care Service,"333 E Miller Drive, Bloomington, IN 47401",,,,
, Bell Trace Health & Living,Healthcare,Assisted Living Facility,"725 Bell Trace Circle, Bloomington, IN 47408",,,,
, IU Health Primary Care - Landmark,Healthcare,Medical Clinic,"550 S Landmark Avenue, Bloomington, IN 47403",,,,
, IU Health Urgent Care - Bloomington,Healthcare,Urgent Care Center,"326 S Woodscrest Drive, Bloomington, IN 47401",,,,
, Aperion Care Monroe,Healthcare,Nursing Home,"120 E Miller Drive, Bloomington, IN 47401",,,,
, IU Health Primary Care - Liberty,Healthcare,Medical Clinic,"1520 Liberty Drive, Bloomington, IN 47403",,,,
, Monroe Hospital,Healthcare,Hospital,"4011 S Monroe Medical Park Blvd, Bloomington, IN 47403",,,,
, Regional Academic Health Center (RAHC),Education,University,"2631 E Discovery Parkway, Bloomington, IN 47408",,,,
, Activate by Everside Health,Healthcare,Medical Clinic,"119 W 7th Street #264, Bloomington, IN 47404",,,,
, Golden LivingCenter - Bloomington,Healthcare,Nursing Home,"155 E Burks Drive, Bloomington, IN 47401",,,,
, The Cook Family Health Center,Healthcare,Medical Center,"402 N Rogers Street, Bloomington, IN 47404",,,,

In [17]:
import pandas as pd

# New healthcare facilities to be added
new_facilities_data = [
    {"Facility": "IU Health Bloomington Hospital", "Facility Group": "Healthcare", "Type": "Hospital", "Location": "2651 E Discovery Parkway, Bloomington, IN 47408"},
    {"Facility": "Brickyard Healthcare - Bloomington Care Center", "Facility Group": "Healthcare", "Type": "Nursing Home", "Location": "155 E Burks Drive, Bloomington, IN 47401"},
    {"Facility": "Bloomington Regional Rehabilitation Hospital", "Facility Group": "Healthcare", "Type": "Specialized Hospital", "Location": "3050 N Lintel Drive, Bloomington, IN 47404"},
    {"Facility": "Hearthstone Health Campus", "Facility Group": "Healthcare", "Type": "Assisted Living Facility", "Location": "3043 N Lintel Drive, Bloomington, IN 47404"},
    {"Facility": "Majestic Care of Bloomington", "Facility Group": "Healthcare", "Type": "Nursing Home", "Location": "1100 S Curry Pike, Bloomington, IN 47403"},
    {"Facility": "Indiana University Student Health Center", "Facility Group": "Healthcare", "Type": "Medical Center", "Location": "600 N Eagleson Avenue, Bloomington, IN 47405"},
    {"Facility": "Bloomington Meadows Hospital", "Facility Group": "Healthcare", "Type": "Mental Health Clinic", "Location": "3600 N Prow Road, Bloomington, IN 47404"},
    {"Facility": "Stonecroft Health Campus", "Facility Group": "Healthcare", "Type": "Assisted Living Facility", "Location": "363 S Fieldstone Boulevard, Bloomington, IN 47403"},
    {"Facility": "HealthNet Bloomington Health Center", "Facility Group": "Healthcare", "Type": "Medical Clinic", "Location": "811 W 2nd Street, Bloomington, IN 47403"},
    {"Facility": "Bloomington Hospital Home Health", "Facility Group": "Healthcare", "Type": "Home Health Care Service", "Location": "333 E Miller Drive, Bloomington, IN 47401"},
    {"Facility": "Bell Trace Health & Living", "Facility Group": "Healthcare", "Type": "Assisted Living Facility", "Location": "725 Bell Trace Circle, Bloomington, IN 47408"},
    {"Facility": "IU Health Primary Care - Landmark", "Facility Group": "Healthcare", "Type": "Medical Clinic", "Location": "550 S Landmark Avenue, Bloomington, IN 47403"},
    {"Facility": "IU Health Urgent Care - Bloomington", "Facility Group": "Healthcare", "Type": "Urgent Care Center", "Location": "326 S Woodscrest Drive, Bloomington, IN 47401"},
    {"Facility": "Aperion Care Monroe", "Facility Group": "Healthcare", "Type": "Nursing Home", "Location": "120 E Miller Drive, Bloomington, IN 47401"},
    {"Facility": "IU Health Primary Care - Liberty", "Facility Group": "Healthcare", "Type": "Medical Clinic", "Location": "1520 Liberty Drive, Bloomington, IN 47403"},
    {"Facility": "Monroe Hospital", "Facility Group": "Healthcare", "Type": "Hospital", "Location": "4011 S Monroe Medical Park Blvd, Bloomington, IN 47403"},
    {"Facility": "Regional Academic Health Center (RAHC)", "Facility Group": "Education", "Type": "University", "Location": "2631 E Discovery Parkway, Bloomington, IN 47408"},
    {"Facility": "Activate by Everside Health", "Facility Group": "Healthcare", "Type": "Medical Clinic", "Location": "119 W 7th Street #264, Bloomington, IN 47404"},
    {"Facility": "Golden LivingCenter - Bloomington", "Facility Group": "Healthcare", "Type": "Nursing Home", "Location": "155 E Burks Drive, Bloomington, IN 47401"},
    {"Facility": "The Cook Family Health Center", "Facility Group": "Healthcare", "Type": "Medical Center", "Location": "402 N Rogers Street, Bloomington, IN 47404"},
]

# Convert to DataFrame with all required columns
new_facilities_df = pd.DataFrame(new_facilities_data)
new_facilities_df["Place ID"] = None
new_facilities_df["X Coordinate"] = None
new_facilities_df["Y Coordinate"] = None
new_facilities_df["Latitude"] = None
new_facilities_df["Longitude"] = None
new_facilities_df["Geometry"] = None

# Reorder columns to match your original DataFrame
column_order = ['Place ID', 'Facility', 'Facility Group', 'Type', 'Location',
                'X Coordinate', 'Y Coordinate', 'Latitude', 'Longitude', 'Geometry']
new_facilities_df = new_facilities_df[column_order]

In [18]:
print(", ".join([f'"{loc}"' for loc in new_facilities_df['Location']]))

"2651 E Discovery Parkway, Bloomington, IN 47408", "155 E Burks Drive, Bloomington, IN 47401", "3050 N Lintel Drive, Bloomington, IN 47404", "3043 N Lintel Drive, Bloomington, IN 47404", "1100 S Curry Pike, Bloomington, IN 47403", "600 N Eagleson Avenue, Bloomington, IN 47405", "3600 N Prow Road, Bloomington, IN 47404", "363 S Fieldstone Boulevard, Bloomington, IN 47403", "811 W 2nd Street, Bloomington, IN 47403", "333 E Miller Drive, Bloomington, IN 47401", "725 Bell Trace Circle, Bloomington, IN 47408", "550 S Landmark Avenue, Bloomington, IN 47403", "326 S Woodscrest Drive, Bloomington, IN 47401", "120 E Miller Drive, Bloomington, IN 47401", "1520 Liberty Drive, Bloomington, IN 47403", "4011 S Monroe Medical Park Blvd, Bloomington, IN 47403", "2631 E Discovery Parkway, Bloomington, IN 47408", "119 W 7th Street #264, Bloomington, IN 47404", "155 E Burks Drive, Bloomington, IN 47401", "402 N Rogers Street, Bloomington, IN 47404"


2651 E Discovery Parkway, Bloomington, IN 47408 => Latitude: 39.17734385, Longitude: -86.50352701223837
155 E Burks Drive, Bloomington, IN 47401 => Latitude: 39.1267477323763, Longitude: -86.5292347818554
3050 N Lintel Drive, Bloomington, IN 47404 => Latitude: 39.25007, Longitude: -86.580849
3043 N Lintel Drive, Bloomington, IN 47404 => Latitude: 39.25007, Longitude: -86.580849
1100 S Curry Pike, Bloomington, IN 47403 => Latitude: 39.149369323991316, Longitude: -86.58255630702538
600 N Eagleson Avenue, Bloomington, IN 47405 => Latitude: 39.17211865, Longitude: -86.51518279610724
3600 N Prow Road, Bloomington, IN 47404 => Latitude: 39.20605315, Longitude: -86.55098737289987
363 S Fieldstone Boulevard, Bloomington, IN 47403 => Latitude: 39.16487, Longitude: -86.605339
811 W 2nd Street, Bloomington, IN 47403 => Latitude: 39.16134305544695, Longitude: -86.54247940838711
333 E Miller Drive, Bloomington, IN 47401 => Latitude: 39.146989899331416, Longitude: -86.52998628059434
725 Bell Trace Circle, Bloomington, IN 47408 => Latitude: 39.1689974, Longitude: -86.4888937
550 S Landmark Avenue, Bloomington, IN 47403 => Latitude: 39.1606926, Longitude: -86.5550396
326 S Woodscrest Drive, Bloomington, IN 47401 => Latitude: 39.16384763118611, Longitude: -86.50255477096619
120 E Miller Drive, Bloomington, IN 47401 => Latitude: 39.14697075345173, Longitude: -86.52673161262301
1520 Liberty Drive, Bloomington, IN 47403 => Latitude: 39.147347, Longitude: -86.577085
4011 S Monroe Medical Park Blvd, Bloomington, IN 47403 => Latitude: 39.1203582, Longitude: -86.57181037497892
2631 E Discovery Parkway, Bloomington, IN 47408 => Latitude: 39.17535409755241, Longitude: -86.49958572570831
119 W 7th Street #264, Bloomington, IN 47404 => Latitude: 39.168632, Longitude: -86.5441565
155 E Burks Drive, Bloomington, IN 47401 => Latitude: 39.1267477323763, Longitude: -86.5292347818554
402 N Rogers Street, Bloomington, IN 47404 => Latitude: 39.1698314, Longitude: -86.53831054245512

In [19]:
# Mapping of address to (Latitude, Longitude)
location_to_coords = {
    "2651 E Discovery Parkway, Bloomington, IN 47408": (39.17734385, -86.50352701223837),
    "155 E Burks Drive, Bloomington, IN 47401": (39.1267477323763, -86.5292347818554),
    "3050 N Lintel Drive, Bloomington, IN 47404": (39.25007, -86.580849),
    "3043 N Lintel Drive, Bloomington, IN 47404": (39.25007, -86.580849),
    "1100 S Curry Pike, Bloomington, IN 47403": (39.149369323991316, -86.58255630702538),
    "600 N Eagleson Avenue, Bloomington, IN 47405": (39.17211865, -86.51518279610724),
    "3600 N Prow Road, Bloomington, IN 47404": (39.20605315, -86.55098737289987),
    "363 S Fieldstone Boulevard, Bloomington, IN 47403": (39.16487, -86.605339),
    "811 W 2nd Street, Bloomington, IN 47403": (39.16134305544695, -86.54247940838711),
    "333 E Miller Drive, Bloomington, IN 47401": (39.146989899331416, -86.52998628059434),
    "725 Bell Trace Circle, Bloomington, IN 47408": (39.1689974, -86.4888937),
    "550 S Landmark Avenue, Bloomington, IN 47403": (39.1606926, -86.5550396),
    "326 S Woodscrest Drive, Bloomington, IN 47401": (39.16384763118611, -86.50255477096619),
    "120 E Miller Drive, Bloomington, IN 47401": (39.14697075345173, -86.52673161262301),
    "1520 Liberty Drive, Bloomington, IN 47403": (39.147347, -86.577085),
    "4011 S Monroe Medical Park Blvd, Bloomington, IN 47403": (39.1203582, -86.57181037497892),
    "2631 E Discovery Parkway, Bloomington, IN 47408": (39.17535409755241, -86.49958572570831),
    "119 W 7th Street #264, Bloomington, IN 47404": (39.168632, -86.5441565),
    "402 N Rogers Street, Bloomington, IN 47404": (39.1698314, -86.53831054245512)
}

# Apply the mapping to add Latitude and Longitude to your DataFrame
new_facilities_df["Latitude"] = new_facilities_df["Location"].map(lambda loc: location_to_coords.get(loc, (None, None))[0])
new_facilities_df["Longitude"] = new_facilities_df["Location"].map(lambda loc: location_to_coords.get(loc, (None, None))[1])

In [20]:
new_facilities_df["Geometry"] = new_facilities_df.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})" if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']) else None,
    axis=1
)

In [21]:
new_facilities_df

Place ID                                        Facility Facility Group  \
0      None                  IU Health Bloomington Hospital     Healthcare   
1      None  Brickyard Healthcare - Bloomington Care Center     Healthcare   
2      None    Bloomington Regional Rehabilitation Hospital     Healthcare   
3      None                       Hearthstone Health Campus     Healthcare   
4      None                    Majestic Care of Bloomington     Healthcare   
5      None        Indiana University Student Health Center     Healthcare   
6      None                    Bloomington Meadows Hospital     Healthcare   
7      None                        Stonecroft Health Campus     Healthcare   
8      None             HealthNet Bloomington Health Center     Healthcare   
9      None                Bloomington Hospital Home Health     Healthcare   
10     None                      Bell Trace Health & Living     Healthcare   
11     None               IU Health Primary Care - Landmark     Healthcare   
12     None             IU Health Urgent Care - Bloomington     Healthcare   
13     None                             Aperion Care Monroe     Healthcare   
14     None                IU Health Primary Care - Liberty     Healthcare   
15     None                                 Monroe Hospital     Healthcare   
16     None          Regional Academic Health Center (RAHC)      Education   
17     None                     Activate by Everside Health     Healthcare   
18     None               Golden LivingCenter - Bloomington     Healthcare   
19     None                   The Cook Family Health Center     Healthcare   

                        Type  \
0                   Hospital   
1               Nursing Home   
2       Specialized Hospital   
3   Assisted Living Facility   
4               Nursing Home   
5             Medical Center   
6       Mental Health Clinic   
7   Assisted Living Facility   
8             Medical Clinic   
9   Home Health Care Service   
10  Assisted Living Facility   
11            Medical Clinic   
12        Urgent Care Center   
13              Nursing Home   
14            Medical Clinic   
15                  Hospital   
16                University   
17            Medical Clinic   
18              Nursing Home   
19            Medical Center   

                                             Location X Coordinate  \
0     2651 E Discovery Parkway, Bloomington, IN 47408         None   
1            155 E Burks Drive, Bloomington, IN 47401         None   
2          3050 N Lintel Drive, Bloomington, IN 47404         None   
3          3043 N Lintel Drive, Bloomington, IN 47404         None   
4            1100 S Curry Pike, Bloomington, IN 47403         None   
5        600 N Eagleson Avenue, Bloomington, IN 47405         None   
6             3600 N Prow Road, Bloomington, IN 47404         None   
7   363 S Fieldstone Boulevard, Bloomington, IN 47403         None   
8             811 W 2nd Street, Bloomington, IN 47403         None   
9           333 E Miller Drive, Bloomington, IN 47401         None   
10       725 Bell Trace Circle, Bloomington, IN 47408         None   
11       550 S Landmark Avenue, Bloomington, IN 47403         None   
12      326 S Woodscrest Drive, Bloomington, IN 47401         None   
13          120 E Miller Drive, Bloomington, IN 47401         None   
14          1520 Liberty Drive, Bloomington, IN 47403         None   
15  4011 S Monroe Medical Park Blvd, Bloomington, ...         None   
16    2631 E Discovery Parkway, Bloomington, IN 47408         None   
17       119 W 7th Street #264, Bloomington, IN 47404         None   
18           155 E Burks Drive, Bloomington, IN 47401         None   
19         402 N Rogers Street, Bloomington, IN 47404         None   

   Y Coordinate   Latitude  Longitude  \
0          None  39.177344 -86.503527   
1          None  39.126748 -86.529235   
2          None  39.250070 -86.580849   
3          None  39.250070 -86.580849   
4          None

In [22]:
# Merge the two DataFrames vertically (stack one below the other)
merged_df = pd.concat([city_fac_bloomington, new_facilities_df], ignore_index=True)

In [23]:
merged_df

Place ID                                Facility    Facility Group  \
0       1561                       Ferguson Dog Park             Parks   
1       5069                          Innovation Lab      City Offices   
2       1795                           Latimer Woods             Parks   
3       5044    Frank Southern Ice Arena Parking Lot  Parking Facility   
4         95               Banneker Community Center             Parks   
..       ...                                     ...               ...   
194     None                         Monroe Hospital        Healthcare   
195     None  Regional Academic Health Center (RAHC)         Education   
196     None             Activate by Everside Health        Healthcare   
197     None       Golden LivingCenter - Bloomington        Healthcare   
198     None           The Cook Family Health Center        Healthcare   

                     Type                                           Location  \
0                Dog Park                               4300 N Stone Mill RD   
1      Government Offices                                    627 N Morton ST   
2    Nature Park/Preserve                         3200 E Buick Cadillac BLVD   
3                 Parking                      N of Frank Southern Ice Arena   
4        Community Center                                       930 W 7th ST   
..                    ...                                                ...   
194              Hospital  4011 S Monroe Medical Park Blvd, Bloomington, ...   
195            University    2631 E Discovery Parkway, Bloomington, IN 47408   
196        Medical Clinic       119 W 7th Street #264, Bloomington, IN 47404   
197          Nursing Home           155 E Burks Drive, Bloomington, IN 47401   
198        Medical Center         402 N Rogers Street, Bloomington, IN 47404   

    X Coordinate Y Coordinate   Latitude  Longitude  \
0        3108927      1443195  39.209444 -86.532102   
1        3107860      1429780  39.172582 -86.536221   
2        3120156      1424789  39.158671 -86.492991   
3        3110466      1419288  39.143733 -86.527257   
4        3105365      1428432  39.168922 -86.545049   
..           ...          ...        ...        ...   
194         None         None  39.120358 -86.571810   
195         None         None  39.175354 -86.499586   
196         None         None  39.168632 -86.544156   
197         None         None  39.126748 -86.529235   
198         None         None  39.169831 -86.538311   

                                         Geometry  
0        POINT (-86.532174816526 39.209402001487)  
1        POINT (-86.536225864906 39.172589612604)  
2        POINT (-86.492971346064 39.158675449588)  
3        POINT (-86.527261036202 39.143740768385)  
4        POINT (-86.545054219197 39.168929719659)  
..                                            ...  
194         POINT (-86.57181037497892 39.1203582)  
195  POINT (-86.49958572570831 39.17535409755241)  
196                 POINT (-86.5441565 39.168632)  
197    POINT (-86.5292347818554 39.1267477323763)  
198         POINT (-86.53831054245512 39.1698314)  

[199 rows x 10 columns]

## Govt and Public Facilities

In [24]:
pub_fac = pd.read_csv('/Users/mohammedpathariya/Downloads/public_works_facilities.csv')

In [25]:
print(", ".join([f'"{loc}"' for loc in pub_fac['Location']]))

"220 E 3rd St, Bloomington, IN", "1469 E 17th St, Bloomington, IN", "301 N College Ave, Bloomington, IN", "1500 N Packing House Rd, Bloomington, IN", "245 W Grimes Ln, Bloomington, IN", "300 E 4th St, Bloomington, IN", "2201 E 3rd St, Bloomington, IN", "1987 S Henderson St, Bloomington, IN", "3953 S Kennedy Dr, Bloomington, IN", "810 N Woodlawn Ave, Bloomington, IN", "209 S Fairfield Dr, Bloomington, IN", "2130 S Kirby Rd, Bloomington, IN", "285 East Rhorer Road, Bloomington, IN", "900 N Curry Pike, Bloomington, IN", "5080 IN-46, Bloomington, IN", "2130 S Kirby Rd, Bloomington, IN", "7606 E State Rd 45, Bloomington, IN", "5081 Old State Rd 37, Bloomington, IN", "520 S Walnut St, Bloomington, IN", "3210 E 10th St, Bloomington, IN", "4738 W Vernal Pike, Bloomington, IN", "Clear Creek, IN", "Bloomington, IN", "119 W 7th St, Bloomington, IN", "885 S College Mall Rd, Bloomington, IN", "1531 S Curry Pike Suite 500, Bloomington, IN", "1531 S Curry Pike Suite 300, Bloomington, IN", "1531 S Cur

220 E 3rd St, Bloomington, IN => Latitude: 39.1643493, Longitude: -86.53151727500001
1469 E 17th St, Bloomington, IN => Latitude: 39.17927895, Longitude: -86.5133414746048
301 N College Ave, Bloomington, IN => Latitude: 39.1690926, Longitude: -86.53522720000001
1500 N Packing House Rd, Bloomington, IN => Latitude: 39.179009, Longitude: -86.563243
245 W Grimes Ln, Bloomington, IN => Latitude: 39.15327803478663, Longitude: -86.53543089245797
300 E 4th St, Bloomington, IN => Latitude: 39.1652852, Longitude: -86.5308885238536
2201 E 3rd St, Bloomington, IN => Latitude: 39.164544, Longitude: -86.50657850660527
1987 S Henderson St, Bloomington, IN => Latitude: 39.14443, Longitude: -86.526853
3953 S Kennedy Dr, Bloomington, IN => Latitude: 39.12248027224351, Longitude: -86.52839244154579
810 N Woodlawn Ave, Bloomington, IN => Latitude: 39.17387865, Longitude: -86.52318631412268
209 S Fairfield Dr, Bloomington, IN => Latitude: 39.1653607, Longitude: -86.56968974717483
2130 S Kirby Rd, Bloomington, IN => Latitude: 39.1636996, Longitude: -86.5291743
285 East Rhorer Road, Bloomington, IN => Latitude: 39.12152914285714, Longitude: -86.52702814285715
900 N Curry Pike, Bloomington, IN => Latitude: 39.174704, Longitude: -86.582916
5080 IN-46, Bloomington, IN => Latitude: 39.2075465, Longitude: -86.6013836
2130 S Kirby Rd, Bloomington, IN => Latitude: 39.1636996, Longitude: -86.5291743
7606 E State Rd 45, Bloomington, IN => Latitude: 39.1862838, Longitude: -86.5240522
5081 Old State Rd 37, Bloomington, IN => Latitude: 39.184303506936104, Longitude: -86.5352558181013
520 S Walnut St, Bloomington, IN => Latitude: 39.16088685503416, Longitude: -86.53375640139382
3210 E 10th St, Bloomington, IN => Latitude: 39.17093825, Longitude: -86.49346124313047
4738 W Vernal Pike, Bloomington, IN => Latitude: 39.179137749999995, Longitude: -86.5574584
Clear Creek, IN => Latitude: 39.1092143, Longitude: -86.5399968
Bloomington, IN => Latitude: 39.1670396, Longitude: -86.5342881
119 W 7th St, Bloomington, IN => Latitude: 39.168323349999994, Longitude: -86.53448956150235
885 S College Mall Rd, Bloomington, IN => Latitude: 39.157243987374336, Longitude: -86.49770370553732
1531 S Curry Pike Suite 500, Bloomington, IN => Latitude: 39.1612988, Longitude: -86.5827063
1531 S Curry Pike Suite 300, Bloomington, IN => Latitude: 39.1612988, Longitude: -86.5827063
1531 S Curry Pike Suite 300, Bloomington, IN => Latitude: 39.1612988, Longitude: -86.5827063
401 N Morton St Suite 260, Bloomington, IN => Latitude: 39.1709259, Longitude: -86.5361163
515 W Patterson Dr, Bloomington, IN => Latitude: 39.158210561294155, Longitude: -86.54588526579478
2620 N Walnut St, Bloomington, IN => Latitude: 39.19266596873702, Longitude: -86.53302570324772
501 N Morton St, Bloomington, IN => Latitude: 39.170582, Longitude: -86.53621
1180 Liberty Dr, Bloomington, IN => Latitude: 39.151003, Longitude: -86.576938
1500 W 15th St, Bloomington, IN => Latitude: 39.17710685, Longitude: -86.55305755579975
213 E Kirkwood Ave, Bloomington, IN => Latitude: 39.1668176, Longitude: -86.53158329737832
333 E Miller Dr, Bloomington, IN => Latitude: 39.146989899331416, Longitude: -86.52998628059434
401 N Morton St, Bloomington, IN => Latitude: 39.1697339, Longitude: -86.5366772
600 E Miller Dr, Bloomington, IN => Latitude: 39.146875, Longitude: -86.526743

In [27]:
# Mapping dictionary from location to (Latitude, Longitude)
location_to_coords_pub = {
    "220 E 3rd St, Bloomington, IN": (39.1643493, -86.53151727500001),
    "1469 E 17th St, Bloomington, IN": (39.17927895, -86.5133414746048),
    "301 N College Ave, Bloomington, IN": (39.1690926, -86.53522720000001),
    "1500 N Packing House Rd, Bloomington, IN": (39.179009, -86.563243),
    "245 W Grimes Ln, Bloomington, IN": (39.15327803478663, -86.53543089245797),
    "300 E 4th St, Bloomington, IN": (39.1652852, -86.5308885238536),
    "2201 E 3rd St, Bloomington, IN": (39.164544, -86.50657850660527),
    "1987 S Henderson St, Bloomington, IN": (39.14443, -86.526853),
    "3953 S Kennedy Dr, Bloomington, IN": (39.12248027224351, -86.52839244154579),
    "810 N Woodlawn Ave, Bloomington, IN": (39.17387865, -86.52318631412268),
    "209 S Fairfield Dr, Bloomington, IN": (39.1653607, -86.56968974717483),
    "2130 S Kirby Rd, Bloomington, IN": (39.1636996, -86.5291743),
    "285 East Rhorer Road, Bloomington, IN": (39.12152914285714, -86.52702814285715),
    "900 N Curry Pike, Bloomington, IN": (39.174704, -86.582916),
    "5080 IN-46, Bloomington, IN": (39.2075465, -86.6013836),
    "7606 E State Rd 45, Bloomington, IN": (39.1862838, -86.5240522),
    "5081 Old State Rd 37, Bloomington, IN": (39.184303506936104, -86.5352558181013),
    "520 S Walnut St, Bloomington, IN": (39.16088685503416, -86.53375640139382),
    "3210 E 10th St, Bloomington, IN": (39.17093825, -86.49346124313047),
    "4738 W Vernal Pike, Bloomington, IN": (39.179137749999995, -86.5574584),
    "Clear Creek, IN": (39.1092143, -86.5399968),
    "Bloomington, IN": (39.1670396, -86.5342881),
    "119 W 7th St, Bloomington, IN": (39.168323349999994, -86.53448956150235),
    "885 S College Mall Rd, Bloomington, IN": (39.157243987374336, -86.49770370553732),
    "1531 S Curry Pike Suite 500, Bloomington, IN": (39.1612988, -86.5827063),
    "1531 S Curry Pike Suite 300, Bloomington, IN": (39.1612988, -86.5827063),
    "401 N Morton St Suite 260, Bloomington, IN": (39.1709259, -86.5361163),
    "515 W Patterson Dr, Bloomington, IN": (39.158210561294155, -86.54588526579478),
    "2620 N Walnut St, Bloomington, IN": (39.19266596873702, -86.53302570324772),
    "501 N Morton St, Bloomington, IN": (39.170582, -86.53621),
    "1180 Liberty Dr, Bloomington, IN": (39.151003, -86.576938),
    "1500 W 15th St, Bloomington, IN": (39.17710685, -86.55305755579975),
    "213 E Kirkwood Ave, Bloomington, IN": (39.1668176, -86.53158329737832),
    "333 E Miller Dr, Bloomington, IN": (39.146989899331416, -86.52998628059434),
    "401 N Morton St, Bloomington, IN": (39.1697339, -86.5366772),
    "600 E Miller Dr, Bloomington, IN": (39.146875, -86.526743),
}

# Add coordinates to the DataFrame
pub_fac["Latitude"] = pub_fac["Location"].map(lambda loc: location_to_coords_pub.get(loc, (None, None))[0])
pub_fac["Longitude"] = pub_fac["Location"].map(lambda loc: location_to_coords_pub.get(loc, (None, None))[1])

In [28]:
pub_fac["Geometry"] = pub_fac.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})" if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']) else None,
    axis=1
)

In [29]:
pub_fac

Facility       Facility Group  \
0                 Bloomington Police Department        Public Safety   
1   Indiana University Police Department (IUPD)        Public Safety   
2            Monroe County Sheriff's Department        Public Safety   
3                          Indiana State Police        Public Safety   
4                 Bloomington Police Substation        Public Safety   
5                   Bloomington Fire Department        Public Safety   
6                   Bloomington Fire Station #4        Public Safety   
7                   Bloomington Fire Station #5        Public Safety   
8    Monroe Fire Protection District Station 22        Public Safety   
9                   Bloomington Fire Station #3        Public Safety   
10                  Bloomington Fire Station #2        Public Safety   
11   Monroe Fire Protection District Station 29        Public Safety   
12              Monroe Fire Protection District        Public Safety   
13       Ellettsville Fire Department Station 8        Public Safety   
14                 Ellettsville Fire Department        Public Safety   
15         Van Buren Fire Department Station 19        Public Safety   
16    Benton Township Volunteer Fire Department        Public Safety   
17                               MFD Station 25        Public Safety   
18                 United States Postal Service  Government Services   
19                 United States Postal Service  Government Services   
20                 United States Postal Service  Government Services   
21                 United States Postal Service  Government Services   
22                          USPS COLLECTION BOX  Government Services   
23                          USPS COLLECTION BOX  Government Services   
24                                The UPS Store  Government Services   
25                       Bloomington BMV Branch  Government Services   
26   Monroe County Division of Family Resources  Government Services   
27        Family Social Services Administration  Government Services   
28      Community & Family Resources Department  Government Services   
29               Social Security Administration  Government Services   
30                Disability Claim Services Inc  Government Services   
31                    Adult Protective Services  Government Services   
32                             Family Solutions  Government Services   
33       South Central Community Action Program  Government Services   
34        Habitat for Humanity of Monroe County  Government Services   
35                    Monroe County WIC Program  Government Services   
36                        Bloomington City Hall  Government Services   
37                City of Bloomington Utilities  Government Services   

                       Type                                      Location  \
0         Police Department                 220 E 3rd St, Bloomington, IN   
1         Police Department               1469 E 17th St, Bloomington, IN   
2      Sheriff's Department            301 N College Ave, Bloomington, IN   
3              State Police      1500 N Packing House Rd, Bloomington, IN   
4         Police Substation              245 W Grimes Ln, Bloomington, IN   
5              Fire Station                 300 E 4th St, Bloomington, IN   
6              Fire Station                2201 E 3rd St, Bloomington, IN   
7              Fire Station          1987 S Henderson St, Bloomington, IN   
8              Fire Station            3953 S Kennedy Dr, Bloomington, IN   
9              Fire Station           810 N Woodlawn Ave, Bloomington, IN   
10             Fire Station           209 S Fairfield Dr, Bloomington, IN   
11             Fire Station              2130 S Kirby Rd, Bloomington, IN   
12             Fire Station         285 East Rhorer Road, Bloomington, IN   
13             Fire Station             900 N Curry Pike, Bloomington, IN   
14             Fire Station                   5080 IN-46, Bloomington, IN  

In [30]:
# Merge the two DataFrames vertically (stack one below the other)
merged_df_pub = pd.concat([merged_df, pub_fac], ignore_index=True)

In [31]:
merged_df_pub

Place ID                                Facility       Facility Group  \
0       1561                       Ferguson Dog Park                Parks   
1       5069                          Innovation Lab         City Offices   
2       1795                           Latimer Woods                Parks   
3       5044    Frank Southern Ice Arena Parking Lot     Parking Facility   
4         95               Banneker Community Center                Parks   
..       ...                                     ...                  ...   
232      NaN  South Central Community Action Program  Government Services   
233      NaN   Habitat for Humanity of Monroe County  Government Services   
234      NaN               Monroe County WIC Program  Government Services   
235      NaN                   Bloomington City Hall  Government Services   
236      NaN           City of Bloomington Utilities  Government Services   

                        Type                             Location  \
0                   Dog Park                 4300 N Stone Mill RD   
1         Government Offices                      627 N Morton ST   
2       Nature Park/Preserve           3200 E Buick Cadillac BLVD   
3                    Parking        N of Frank Southern Ice Arena   
4           Community Center                         930 W 7th ST   
..                       ...                                  ...   
232  Non-profit Organization      1500 W 15th St, Bloomington, IN   
233  Non-profit Organization  213 E Kirkwood Ave, Bloomington, IN   
234   Social Services Office     333 E Miller Dr, Bloomington, IN   
235   City Government Office     401 N Morton St, Bloomington, IN   
236         Utilities Office     600 E Miller Dr, Bloomington, IN   

    X Coordinate Y Coordinate   Latitude  Longitude  \
0        3108927      1443195  39.209444 -86.532102   
1        3107860      1429780  39.172582 -86.536221   
2        3120156      1424789  39.158671 -86.492991   
3        3110466      1419288  39.143733 -86.527257   
4        3105365      1428432  39.168922 -86.545049   
..           ...          ...        ...        ...   
232          NaN          NaN  39.177107 -86.553058   
233          NaN          NaN  39.166818 -86.531583   
234          NaN          NaN  39.146990 -86.529986   
235          NaN          NaN  39.169734 -86.536677   
236          NaN          NaN  39.146875 -86.526743   

                                          Geometry  
0         POINT (-86.532174816526 39.209402001487)  
1         POINT (-86.536225864906 39.172589612604)  
2         POINT (-86.492971346064 39.158675449588)  
3         POINT (-86.527261036202 39.143740768385)  
4         POINT (-86.545054219197 39.168929719659)  
..                                             ...  
232         POINT (-86.55305755579975 39.17710685)  
233          POINT (-86.53158329737832 39.1668176)  
234  POINT (-86.52998628059434 39.146989899331416)  
235                 POINT (-86.5366772 39.1697339)  
236                   POINT (-86.526743 39.146875)  

[237 rows x 10 columns]

## Shopping Data Grocery Stores

In [32]:
grocery_fac = pd.read_csv('/Users/mohammedpathariya/Downloads/public_grocery_facilities.csv')

In [33]:
print(", ".join([f'"{loc}"' for loc in grocery_fac['Location']]))

"106 E 2nd St, Bloomington, IN", "2812 E 3rd St, Bloomington, IN", "2901 E Covenanter Dr, Bloomington, IN", "528 S College Ave, Bloomington, IN", "3220 E 3rd St, Bloomington, IN", "902 W Kirkwood Ave, Bloomington, IN", "6050 E State Rd 45, Bloomington, IN", "1825 N Kinser Pike, Bloomington, IN", "3600 W 3rd St, Bloomington, IN", "1175 S College Mall Rd, Bloomington, IN", "421 E 3rd St #2, Bloomington, IN", "2646 E 10th St, Bloomington, IN", "2556 E 3rd St, Bloomington, IN", "316 W 6th St, Bloomington, IN", "401 N Morton St, Bloomington, IN", "4025 S Old State Rd 37, Bloomington, IN", "500 Liberty Dr, Bloomington, IN", "1915 S Walnut St, Bloomington, IN", "115 S IN-46 Suite E, Bloomington, IN", "408 E 4th St, Bloomington, IN", "800 N Union St, Bloomington, IN", "827 W 14th Ct, Bloomington, IN", "2333 W Industrial Park Dr, Bloomington, IN", "1100 W Allen St, Bloomington, IN", "1515 S Rogers St, Bloomington, IN", "219 E 4th St, Bloomington, IN", "1010 S Walnut St A, Bloomington, IN", "924

106 E 2nd St, Bloomington, IN => Latitude: 39.16128506122449, Longitude: -86.53343263265306
2812 E 3rd St, Bloomington, IN => Latitude: 39.16328215, Longitude: -86.49599495105925
2901 E Covenanter Dr, Bloomington, IN => Latitude: 39.1556955, Longitude: -86.49480742912317
528 S College Ave, Bloomington, IN => Latitude: 39.15985885, Longitude: -86.53557942790022
3220 E 3rd St, Bloomington, IN => Latitude: 39.163904, Longitude: -86.4910644
902 W Kirkwood Ave, Bloomington, IN => Latitude: 39.16674316580055, Longitude: -86.5439273674845
6050 E State Rd 45, Bloomington, IN => Latitude: 39.1862838, Longitude: -86.5240522
1825 N Kinser Pike, Bloomington, IN => Latitude: 39.18762515, Longitude: -86.54005336377776
3600 W 3rd St, Bloomington, IN => Latitude: 39.166061299999996, Longitude: -86.57954996362508
1175 S College Mall Rd, Bloomington, IN => Latitude: 39.15373875, Longitude: -86.49522157943169
421 E 3rd St #2, Bloomington, IN => Latitude: 39.1649491, Longitude: -86.5287363
2646 E 10th St, Bloomington, IN => Latitude: 39.1712374, Longitude: -86.5003164
2556 E 3rd St, Bloomington, IN => Latitude: 39.16415343434344, Longitude: -86.50215791919192
316 W 6th St, Bloomington, IN => Latitude: 39.16791164999999, Longitude: -86.53715907506235
401 N Morton St, Bloomington, IN => Latitude: 39.1697339, Longitude: -86.5366772
4025 S Old State Rd 37, Bloomington, IN => Latitude: 39.12028275, Longitude: -86.52934020634686
500 Liberty Dr, Bloomington, IN => Latitude: 39.151212, Longitude: -86.576864
1915 S Walnut St, Bloomington, IN => Latitude: 39.1457916927377, Longitude: -86.5322322028014
115 S IN-46 Suite E, Bloomington, IN => Latitude: 39.1599902, Longitude: -86.490383
408 E 4th St, Bloomington, IN => Latitude: 39.1653589, Longitude: -86.52932009299789
800 N Union St, Bloomington, IN => Latitude: 39.17360145, Longitude: -86.50882761006616
827 W 14th Ct, Bloomington, IN => Latitude: 39.175728128204376, Longitude: -86.5437536665985
2333 W Industrial Park Dr, Bloomington, IN => Latitude: 39.17507766809507, Longitude: -86.56700591872043
1100 W Allen St, Bloomington, IN => Latitude: 39.155735, Longitude: -86.544477
1515 S Rogers St, Bloomington, IN => Latitude: 39.15036019069062, Longitude: -86.53868127054612
219 E 4th St, Bloomington, IN => Latitude: 39.16582585, Longitude: -86.53198648055685
1010 S Walnut St A, Bloomington, IN => Latitude: 39.155374466272995, Longitude: -86.53380375671252
924 W 17th St Suite C, Bloomington, IN => Latitude: 39.179114, Longitude: -86.543911
421 S Curry Pike, Bloomington, IN => Latitude: 39.163635408163266, Longitude: -86.58264691836735
321 N Rogers St, Bloomington, IN => Latitude: 39.16885461600526, Longitude: -86.53876018057748
1007 N Summit St, Bloomington, IN => Latitude: 39.17539935, Longitude: -86.5483603965919
919 S Rogers St, Bloomington, IN => Latitude: 39.1572247823773, Longitude: -86.53858278190908

In [34]:
# Dictionary mapping location to (latitude, longitude)
location_coords = {
    "106 E 2nd St, Bloomington, IN": (39.16128506122449, -86.53343263265306),
    "2812 E 3rd St, Bloomington, IN": (39.16328215, -86.49599495105925),
    "2901 E Covenanter Dr, Bloomington, IN": (39.1556955, -86.49480742912317),
    "528 S College Ave, Bloomington, IN": (39.15985885, -86.53557942790022),
    "3220 E 3rd St, Bloomington, IN": (39.163904, -86.4910644),
    "902 W Kirkwood Ave, Bloomington, IN": (39.16674316580055, -86.5439273674845),
    "6050 E State Rd 45, Bloomington, IN": (39.1862838, -86.5240522),
    "1825 N Kinser Pike, Bloomington, IN": (39.18762515, -86.54005336377776),
    "3600 W 3rd St, Bloomington, IN": (39.1660613, -86.57954996362508),
    "1175 S College Mall Rd, Bloomington, IN": (39.15373875, -86.49522157943169),
    "421 E 3rd St #2, Bloomington, IN": (39.1649491, -86.5287363),
    "2646 E 10th St, Bloomington, IN": (39.1712374, -86.5003164),
    "2556 E 3rd St, Bloomington, IN": (39.16415343434344, -86.50215791919192),
    "316 W 6th St, Bloomington, IN": (39.16791165, -86.53715907506235),
    "401 N Morton St, Bloomington, IN": (39.1697339, -86.5366772),
    "4025 S Old State Rd 37, Bloomington, IN": (39.12028275, -86.52934020634686),
    "500 Liberty Dr, Bloomington, IN": (39.151212, -86.576864),
    "1915 S Walnut St, Bloomington, IN": (39.1457916927377, -86.5322322028014),
    "115 S IN-46 Suite E, Bloomington, IN": (39.1599902, -86.490383),
    "408 E 4th St, Bloomington, IN": (39.1653589, -86.52932009299789),
    "800 N Union St, Bloomington, IN": (39.17360145, -86.50882761006616),
    "827 W 14th Ct, Bloomington, IN": (39.175728128204376, -86.5437536665985),
    "2333 W Industrial Park Dr, Bloomington, IN": (39.17507766809507, -86.56700591872043),
    "1100 W Allen St, Bloomington, IN": (39.155735, -86.544477),
    "1515 S Rogers St, Bloomington, IN": (39.15036019069062, -86.53868127054612),
    "219 E 4th St, Bloomington, IN": (39.16582585, -86.53198648055685),
    "1010 S Walnut St A, Bloomington, IN": (39.155374466272995, -86.53380375671252),
    "924 W 17th St Suite C, Bloomington, IN": (39.179114, -86.543911),
    "421 S Curry Pike, Bloomington, IN": (39.163635408163266, -86.58264691836735),
    "321 N Rogers St, Bloomington, IN": (39.16885461600526, -86.53876018057748),
    "1007 N Summit St, Bloomington, IN": (39.17539935, -86.5483603965919),
    "919 S Rogers St, Bloomington, IN": (39.1572247823773, -86.53858278190908)
}

# Update Latitude and Longitude columns in grocery_fac
grocery_fac["Latitude"] = grocery_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[0])
grocery_fac["Longitude"] = grocery_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[1])

In [35]:
grocery_fac["Geometry"] = grocery_fac.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})" if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']) else None,
    axis=1
)

In [36]:
grocery_fac

Facility            Facility Group  \
0                          World Foods Market  Retail & Public Services   
1                                 Fresh Thyme  Retail & Public Services   
2                 B-Town International Market  Retail & Public Services   
3                                      Kroger  Retail & Public Services   
4                  Bloomingfoods Co-op Market  Retail & Public Services   
5            Bloomington Farm Stop Collective  Retail & Public Services   
6                             Lakeside Market  Retail & Public Services   
7                                      Kroger  Retail & Public Services   
8                          Fresh Thyme Market  Retail & Public Services   
9                                      Kroger  Retail & Public Services   
10                        Little Italy Market  Retail & Public Services   
11                     Rong Cheng Supermarket  Retail & Public Services   
12           Apna Bazaar International Market  Retail & Public Services   
13                 Bloomingfoods Co-op Market  Retail & Public Services   
14      Bloomington Community Farmers' Market  Retail & Public Services   
15                                     Kroger  Retail & Public Services   
16                                     Kroger  Retail & Public Services   
17                     La Bodega Latin Market  Retail & Public Services   
18                        The Butcher's Block  Retail & Public Services   
19            4th Street International Market  Retail & Public Services   
20               Crimson Cupboard Food Pantry  Retail & Public Services   
21            Monroe County United Ministries  Retail & Public Services   
22                    Hoosier Hills Food Bank  Retail & Public Services   
23                   Mother Hubbards Cupboard  Retail & Public Services   
24                          Community Kitchen  Retail & Public Services   
25                      FUMC Wednesday Pantry  Retail & Public Services   
26                 Bobby's Pantry Food Pantry  Retail & Public Services   
27   Bloomington Township Trustee Food Pantry  Retail & Public Services   
28           Tabitha's Storehouse Food Pantry  Retail & Public Services   
29  Feed The Needy - Food Distribution Center  Retail & Public Services   
30            Crestmont Community Food Pantry  Retail & Public Services   
31   Shelter, Inc. - Food Distribution Center  Retail & Public Services   

                        Type                                    Location  \
0              Grocery Store               106 E 2nd St, Bloomington, IN   
1              Grocery Store              2812 E 3rd St, Bloomington, IN   
2              Grocery Store       2901 E Covenanter Dr, Bloomington, IN   
3              Grocery Store          528 S College Ave, Bloomington, IN   
4              Grocery Store              3220 E 3rd St, Bloomington, IN   
5                  Farm Shop         902 W Kirkwood Ave, Bloomington, IN   
6              Grocery Store         6050 E State Rd 45, Bloomington, IN   
7              Grocery Store         1825 N Kinser Pike, Bloomington, IN   
8              Grocery Store              3600 W 3rd St, Bloomington, IN   
9              Grocery Store     1175 S College Mall Rd, Bloomington, IN   
10     Italian Grocery Store            421 E 3rd St #2, Bloomington, IN   
11       Asian Grocery Store             2646 E 10th St, Bloomington, IN   
12      Indian Grocery Store              2556 E 3rd St, Bloomington, IN   
13             Grocery Store               316 W 6th St, Bloomington, IN   
14           Farmers' Market            401 N Morton St, Bloomington, IN   
15             Grocery Store     4025 S Old State Rd 37, Bloomington, IN   
16             Grocery Store             500 Liberty Dr, Bloomington, IN   
17                    Bakery           1915 S Walnut St, Bloomington, IN   
18              Butcher Shop        115 S IN-46 Suite E, Bloomington, IN   
19             Grocery Store             

In [37]:
# Merge the two DataFrames vertically (stack one below the other)
merged_df_grocery = pd.concat([merged_df_pub, grocery_fac], ignore_index=True)

In [38]:
merged_df_grocery

Place ID                                   Facility  \
0       1561                          Ferguson Dog Park   
1       5069                             Innovation Lab   
2       1795                              Latimer Woods   
3       5044       Frank Southern Ice Arena Parking Lot   
4         95                  Banneker Community Center   
..       ...                                        ...   
264      NaN   Bloomington Township Trustee Food Pantry   
265      NaN           Tabitha's Storehouse Food Pantry   
266      NaN  Feed The Needy - Food Distribution Center   
267      NaN            Crestmont Community Food Pantry   
268      NaN   Shelter, Inc. - Food Distribution Center   

               Facility Group                  Type  \
0                       Parks              Dog Park   
1                City Offices    Government Offices   
2                       Parks  Nature Park/Preserve   
3            Parking Facility               Parking   
4                       Parks      Community Center   
..                        ...                   ...   
264  Retail & Public Services             Food Bank   
265  Retail & Public Services             Food Bank   
266  Retail & Public Services             Food Bank   
267  Retail & Public Services             Food Bank   
268  Retail & Public Services             Food Bank   

                                   Location X Coordinate Y Coordinate  \
0                      4300 N Stone Mill RD      3108927      1443195   
1                           627 N Morton ST      3107860      1429780   
2                3200 E Buick Cadillac BLVD      3120156      1424789   
3             N of Frank Southern Ice Arena      3110466      1419288   
4                              930 W 7th ST      3105365      1428432   
..                                      ...          ...          ...   
264  924 W 17th St Suite C, Bloomington, IN          NaN          NaN   
265       421 S Curry Pike, Bloomington, IN          NaN          NaN   
266        321 N Rogers St, Bloomington, IN          NaN          NaN   
267       1007 N Summit St, Bloomington, IN          NaN          NaN   
268        919 S Rogers St, Bloomington, IN          NaN          NaN   

      Latitude  Longitude                                       Geometry  
0    39.209444 -86.532102       POINT (-86.532174816526 39.209402001487)  
1    39.172582 -86.536221       POINT (-86.536225864906 39.172589612604)  
2    39.158671 -86.492991       POINT (-86.492971346064 39.158675449588)  
3    39.143733 -86.527257       POINT (-86.527261036202 39.143740768385)  
4    39.168922 -86.545049       POINT (-86.545054219197 39.168929719659)  
..         ...        ...                                            ...  
264  39.179114 -86.543911                   POINT (-86.543911 39.179114)  
265  39.163635 -86.582647  POINT (-86.58264691836735 39.163635408163266)  
266  39.168855 -86.538760   POINT (-86.53876018057748 39.16885461600526)  
267  39.175399 -86.548360          POINT (-86.5483603965919 39.17539935)  
268  39.157225 -86.538583    POINT (-86.53858278190908 39.1572247823773)  

[269 rows x 10 columns]

## Restaurants

In [39]:
rest_fac = pd.read_csv('/Users/mohammedpathariya/Downloads/restaurant_facilities_bloomington_complete.csv')

In [40]:
print(", ".join([f'"{loc}"' for loc in rest_fac['Location']]))

"116 N Grant St", "101 W Kirkwood Ave Suite 021, Lower Level", "106 W 6th St", "3115 S Sare Rd", "209 S Grant St", "405 W Patterson Dr", "2608 E 10th St", "108 E Kirkwood Ave", "407 W Patterson Dr", "514 E Kirkwood Ave", "412 E 6th St", "2800 E Buick Cadillac Blvd", "600 E Hillside Dr", "121 N College Ave", "102 E Kirkwood Ave", "350 W 11th St", "614 E 2nd St", "214 W Kirkwood Ave", "505 W 17th St", "405 E 4th St", "216 S Indiana Ave", "210 S Grant St", "221 E Kirkwood Ave Ste 1", "114 S Indiana Ave", "301 E 3rd St", "413 E 4th St", "308 W 6th St", "430 E 4th St", "408 E 4th St", "419 E Kirkwood Ave", "100 E Kirkwood Ave", "300 E 3rd St", "900 E 7th St", "223 W 6th St", "106 N Walnut St", "125 N College Ave", "423 E Kirkwood Ave", "1505 S Piazza Dr", "116 S Franklin Rd", "409 E 4th St", "302 N Walnut St", "430 E Kirkwood Ave Unit 6", "4600 State Hwy 446", "1131 S College Mall Rd", "2620 E 3rd St", "250 S Washington St", "126 S Franklin Rd", "254 N Walnut St", "2500 W 3rd St", "108 E Ki

In [41]:
rest_fac

Facility  \
0                    Big Woods Bloomington   
1                          Brightside Cafe   
2                                Che Bello   
3                       Half Bottle Bistro   
4                Marco and Polo Restaurant   
5                           Southern Stone   
6                                     Hive   
7                          FARMbloomington   
8                    Feast Market & Cellar   
9                         Lennie's Brewpub   
10                          Runcible Spoon   
11                  Vivencia Latín Flavors   
12                   Feta Kitchen and Cafe   
13                  SmokeWorks Bloomington   
14                             Uptown Cafe   
15                      Upland Brewing Co.   
16                      The Elm Restaurant   
17                             Crazy Horse   
18                Smokin' Jack's Rib Shack   
19                           Blooming Thai   
20                                Chow Bar   
21                               Cafe Bali   
22                          Fat Dan's Deli   
23              BuffaLouie's at The Gables   
24                            Cafe Turkuaz   
25                   Kimu Asian Restaurant   
26                           Le Petit Cafe   
27                              Siam House   
28                                    Dats   
29                            Osteria Rago   
30                            Trojan Horse   
31                      Uncle Wang's Alley   
32                           The Vault Pub   
33                   Janko's Little Zagreb   
34                            Malibu Grill   
35              Social Cantina Bloomington   
36                      Nick's English Hut   
37                                  C3 Bar   
38                Riviera Maya Bloomington   
39                        Korea Restaurant   
40                      Yogi's Bloomington   
41                Yatagarasu - Bloomington   
42                  Scenic View Restaurant   
43  Truffles Fine Cuisine & 56 Degrees Bar   
44    DeAngelo's Italian Creole Restaurant   
45                Da Vinci Pizza and Pasta   
46               Cheddar's Scratch Kitchen   
47                          La Una Cantina   
48                              Cozy Table   
49                             Root Cellar   
50                       Samira Restaurant   
51                          The Orbit Room   
52             BJ's Restaurant & Brewhouse   
53                          The Tudor Room   
54                          Taste of India   
55                       Asuka Steak House   
56              BRU Burger Bar Bloomington   
57            Cloverleaf Family Restaurant   
58             Metal Works Brewing Company   
59                 Little Tibet Restaurant   

                                     Location Facility Group             Type  \
0                              116 N Grant St     Restaurant         American   
1   101 W Kirkwood Ave Suite 021, Lower Level     Restaurant      Gluten Free   
2                                106 W 6th St     Restaurant          Italian   
3                              3115 S Sare Rd     Restaurant         American   
4                              209 S Grant St     Restaurant           Uyghur   
5                          405 W Patterson Dr     Restaurant          Mexican   
6                              2608 E 10th St     Restaurant         American   
7                          108 E Kirkwood Ave     Restaurant         American   
8                          407 W Patterson Dr     Restaurant         American   
9                          514 E Kirkwood Ave     Restaurant          Brewpub   
10                               412 E 6th St     Restaurant         American   
11                 2800 E Buick Cadillac Blvd     Restaurant            Latin   
12                          600 E Hillside Dr     Restaurant    Mediterranean   
13                          121 N College Ave     Restaurant         American   
14          

In [42]:
# Dictionary mapping location to (latitude, longitude)
location_coords = {
    "116 N Grant St": (39.16713145, -86.52958997532201),
    "101 W Kirkwood Ave Suite 021, Lower Level": (39.1662847, -86.5342397),
    "106 W 6th St": (39.167808, -86.53388650748555),
    "3115 S Sare Rd": (39.13318445, -86.49778373505043),
    "209 S Grant St": (39.1652076, -86.5295993),
    "405 W Patterson Dr": (-37.532739780531834, 144.99324856385476),
    "2608 E 10th St": (39.1707541, -86.5011251),
    "108 E Kirkwood Ave": (41.56544225242719, -93.61310635922331),
    "407 W Patterson Dr": (-37.532739780531834, 144.99324856385476),
    "514 E Kirkwood Ave": (39.1663999, -86.5274963),
    "412 E 6th St": (30.2670541, -97.7387385),
    "2800 E Buick Cadillac Blvd": (39.1577154, -86.49727255616494),
    "600 E Hillside Dr": (39.150280800000004, -86.52663570279259),
    "121 N College Ave": (39.1673149, -86.5352501161498),
    "102 E Kirkwood Ave": (41.56544274757282, -93.6132636407767),
    "350 W 11th St": (39.7825396, -86.16589426392832),
    "614 E 2nd St": (40.63620635, -73.97726331012974),
    "214 W Kirkwood Ave": (39.16688485, -86.53570447663886),
    "505 W 17th St": (39.1786817, -86.5386954),
    "405 E 4th St": (39.165745900000005, -86.52947146728263),
    "216 S Indiana Ave": (39.1648076, -86.5271993),
    "210 S Grant St": (39.165161600000005, -86.5300562),
    "221 E Kirkwood Ave Ste 1": (39.1669058, -86.5312914),
    "114 S Indiana Ave": (39.1659572, -86.52713420018262),
    "301 E 3rd St": (30.2653919, -97.7428231),
    "413 E 4th St": (40.6420006, -73.9760409),
    "308 W 6th St": (39.1677962, -86.53659825297382),
    "430 E 4th St": (40.64160975, -73.97638950450718),
    "408 E 4th St": (40.642112049999994, -73.9764533347408),
    "419 E Kirkwood Ave": (39.16662676015101, -86.52941924706646),
    "100 E Kirkwood Ave": (41.565442912621364, -93.61331606796116),
    "300 E 3rd St": (40.72101325, -73.97949872019987),
    "900 E 7th St": (30.2665513, -97.73303094394606),
    "223 W 6th St": (43.449224, -76.512878),
    "106 N Walnut St": (38.8359392, -104.83455068034019),
    "125 N College Ave": (39.76864479862455, -86.14571244120967),
    "423 E Kirkwood Ave": (39.1668531, -86.52874212500001),
    "1505 S Piazza Dr": (39.149453449999996, -86.49956168139957),
    "116 S Franklin Rd": (39.1673914, -86.57158753762494),
    "409 E 4th St": (40.64207655, -73.97595423531097),
    "302 N Walnut St": (39.1687029, -86.5333932),
    "430 E Kirkwood Ave Unit 6": (40.660102121329366, -73.5482266929907),
    "4600 State Hwy 446": (50.464884116274135, 5.2501288360982015),
    "1131 S College Mall Rd": (39.15468575, -86.49560015511489),
    "2620 E 3rd St": (34.040090469387756, -118.20849808163265),
    "250 S Washington St": (39.287942, -76.5891927051226),
    "126 S Franklin Rd": (39.1660289, -86.5714171),
    "254 N Walnut St": (39.16836365, -86.53323192483435),
    "2500 W 3rd St": (39.833492, -75.3880446),
    "107 N College Ave #001": (39.16691985, -86.53526701832776),
    "411 S College Mall Rd": (39.1627457, -86.49758205531376),
    "316 E 4th St": (25.82545735, -80.27440344925142),
    "2632 E 3rd St": (34.04003255102041, -118.20836853061225),
    "229 S Grant St Suite 1": (45.50717851010966, -122.67639845541511),
    "4023 W 3rd St": (39.1640057, -86.5841895),
    "108 E 6th St": (43.4572455, -76.5018515),
    "415 E 4th St": (40.6419679, -73.9760349),
}

# Update Latitude and Longitude columns in grocery_fac
rest_fac["Latitude"] = rest_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[0])
rest_fac["Longitude"] = rest_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[1])

In [43]:
rest_fac["Geometry"] = grocery_fac.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})" if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']) else None,
    axis=1
)

In [44]:
rest_fac

Facility  \
0                    Big Woods Bloomington   
1                          Brightside Cafe   
2                                Che Bello   
3                       Half Bottle Bistro   
4                Marco and Polo Restaurant   
5                           Southern Stone   
6                                     Hive   
7                          FARMbloomington   
8                    Feast Market & Cellar   
9                         Lennie's Brewpub   
10                          Runcible Spoon   
11                  Vivencia Latín Flavors   
12                   Feta Kitchen and Cafe   
13                  SmokeWorks Bloomington   
14                             Uptown Cafe   
15                      Upland Brewing Co.   
16                      The Elm Restaurant   
17                             Crazy Horse   
18                Smokin' Jack's Rib Shack   
19                           Blooming Thai   
20                                Chow Bar   
21                               Cafe Bali   
22                          Fat Dan's Deli   
23              BuffaLouie's at The Gables   
24                            Cafe Turkuaz   
25                   Kimu Asian Restaurant   
26                           Le Petit Cafe   
27                              Siam House   
28                                    Dats   
29                            Osteria Rago   
30                            Trojan Horse   
31                      Uncle Wang's Alley   
32                           The Vault Pub   
33                   Janko's Little Zagreb   
34                            Malibu Grill   
35              Social Cantina Bloomington   
36                      Nick's English Hut   
37                                  C3 Bar   
38                Riviera Maya Bloomington   
39                        Korea Restaurant   
40                      Yogi's Bloomington   
41                Yatagarasu - Bloomington   
42                  Scenic View Restaurant   
43  Truffles Fine Cuisine & 56 Degrees Bar   
44    DeAngelo's Italian Creole Restaurant   
45                Da Vinci Pizza and Pasta   
46               Cheddar's Scratch Kitchen   
47                          La Una Cantina   
48                              Cozy Table   
49                             Root Cellar   
50                       Samira Restaurant   
51                          The Orbit Room   
52             BJ's Restaurant & Brewhouse   
53                          The Tudor Room   
54                          Taste of India   
55                       Asuka Steak House   
56              BRU Burger Bar Bloomington   
57            Cloverleaf Family Restaurant   
58             Metal Works Brewing Company   
59                 Little Tibet Restaurant   

                                     Location Facility Group             Type  \
0                              116 N Grant St     Restaurant         American   
1   101 W Kirkwood Ave Suite 021, Lower Level     Restaurant      Gluten Free   
2                                106 W 6th St     Restaurant          Italian   
3                              3115 S Sare Rd     Restaurant         American   
4                              209 S Grant St     Restaurant           Uyghur   
5                          405 W Patterson Dr     Restaurant          Mexican   
6                              2608 E 10th St     Restaurant         American   
7                          108 E Kirkwood Ave     Restaurant         American   
8                          407 W Patterson Dr     Restaurant         American   
9                          514 E Kirkwood Ave     Restaurant          Brewpub   
10                               412 E 6th St     Restaurant         American   
11                 2800 E Buick Cadillac Blvd     Restaurant            Latin   
12                          600 E Hillside Dr     Restaurant    Mediterranean   
13                          121 N College Ave     Restaurant         American   
14          

In [45]:
# Create a new standardized dictionary with lowercase, stripped keys
standardized_coords = {
    k.strip().lower(): v for k, v in location_coords.items()
}

# Apply standardization to the DataFrame Location column
rest_fac["std_location"] = rest_fac["Location"].str.strip().str.lower()

# Map using the standardized keys
rest_fac["Latitude"] = rest_fac["std_location"].map(lambda x: standardized_coords.get(x, (None, None))[0])
rest_fac["Longitude"] = rest_fac["std_location"].map(lambda x: standardized_coords.get(x, (None, None))[1])

# Generate Geometry column
rest_fac["Geometry"] = rest_fac.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})"
    if pd.notnull(row["Latitude"]) and pd.notnull(row["Longitude"])
    else None,
    axis=1
)

# Optional: Drop the helper column
rest_fac.drop(columns=["std_location"], inplace=True)

In [46]:
rest_fac

Facility  \
0                    Big Woods Bloomington   
1                          Brightside Cafe   
2                                Che Bello   
3                       Half Bottle Bistro   
4                Marco and Polo Restaurant   
5                           Southern Stone   
6                                     Hive   
7                          FARMbloomington   
8                    Feast Market & Cellar   
9                         Lennie's Brewpub   
10                          Runcible Spoon   
11                  Vivencia Latín Flavors   
12                   Feta Kitchen and Cafe   
13                  SmokeWorks Bloomington   
14                             Uptown Cafe   
15                      Upland Brewing Co.   
16                      The Elm Restaurant   
17                             Crazy Horse   
18                Smokin' Jack's Rib Shack   
19                           Blooming Thai   
20                                Chow Bar   
21                               Cafe Bali   
22                          Fat Dan's Deli   
23              BuffaLouie's at The Gables   
24                            Cafe Turkuaz   
25                   Kimu Asian Restaurant   
26                           Le Petit Cafe   
27                              Siam House   
28                                    Dats   
29                            Osteria Rago   
30                            Trojan Horse   
31                      Uncle Wang's Alley   
32                           The Vault Pub   
33                   Janko's Little Zagreb   
34                            Malibu Grill   
35              Social Cantina Bloomington   
36                      Nick's English Hut   
37                                  C3 Bar   
38                Riviera Maya Bloomington   
39                        Korea Restaurant   
40                      Yogi's Bloomington   
41                Yatagarasu - Bloomington   
42                  Scenic View Restaurant   
43  Truffles Fine Cuisine & 56 Degrees Bar   
44    DeAngelo's Italian Creole Restaurant   
45                Da Vinci Pizza and Pasta   
46               Cheddar's Scratch Kitchen   
47                          La Una Cantina   
48                              Cozy Table   
49                             Root Cellar   
50                       Samira Restaurant   
51                          The Orbit Room   
52             BJ's Restaurant & Brewhouse   
53                          The Tudor Room   
54                          Taste of India   
55                       Asuka Steak House   
56              BRU Burger Bar Bloomington   
57            Cloverleaf Family Restaurant   
58             Metal Works Brewing Company   
59                 Little Tibet Restaurant   

                                     Location Facility Group             Type  \
0                              116 N Grant St     Restaurant         American   
1   101 W Kirkwood Ave Suite 021, Lower Level     Restaurant      Gluten Free   
2                                106 W 6th St     Restaurant          Italian   
3                              3115 S Sare Rd     Restaurant         American   
4                              209 S Grant St     Restaurant           Uyghur   
5                          405 W Patterson Dr     Restaurant          Mexican   
6                              2608 E 10th St     Restaurant         American   
7                          108 E Kirkwood Ave     Restaurant         American   
8                          407 W Patterson Dr     Restaurant         American   
9                          514 E Kirkwood Ave     Restaurant          Brewpub   
10                               412 E 6th St     Restaurant         American   
11                 2800 E Buick Cadillac Blvd     Restaurant            Latin   
12                          600 E Hillside Dr     Restaurant    Mediterranean   
13                          121 N College Ave     Restaurant         American   
14          

In [47]:
# Merge the two DataFrames vertically (stack one below the other)
merged_df_rest = pd.concat([merged_df_grocery, rest_fac], ignore_index=True)

In [48]:
merged_df_rest

Place ID                              Facility    Facility Group  \
0       1561                     Ferguson Dog Park             Parks   
1       5069                        Innovation Lab      City Offices   
2       1795                         Latimer Woods             Parks   
3       5044  Frank Southern Ice Arena Parking Lot  Parking Facility   
4         95             Banneker Community Center             Parks   
..       ...                                   ...               ...   
324      NaN                     Asuka Steak House        Restaurant   
325      NaN            BRU Burger Bar Bloomington        Restaurant   
326      NaN          Cloverleaf Family Restaurant        Restaurant   
327      NaN           Metal Works Brewing Company        Restaurant   
328      NaN               Little Tibet Restaurant        Restaurant   

                     Type                       Location X Coordinate  \
0                Dog Park           4300 N Stone Mill RD      3108927   
1      Government Offices                627 N Morton ST      3107860   
2    Nature Park/Preserve     3200 E Buick Cadillac BLVD      3120156   
3                 Parking  N of Frank Southern Ice Arena      3110466   
4        Community Center                   930 W 7th ST      3105365   
..                    ...                            ...          ...   
324              Japanese                  2632 E 3rd St          NaN   
325             Hamburger         229 S Grant St Suite 1          NaN   
326       Family-friendly                  4023 W 3rd St          NaN   
327               Brewpub                   108 E 6th St          NaN   
328               Tibetan                   415 E 4th St          NaN   

    Y Coordinate   Latitude   Longitude  \
0        1443195  39.209444  -86.532102   
1        1429780  39.172582  -86.536221   
2        1424789  39.158671  -86.492991   
3        1419288  39.143733  -86.527257   
4        1428432  39.168922  -86.545049   
..           ...        ...         ...   
324          NaN  34.040033 -118.208369   
325          NaN  45.507179 -122.676398   
326          NaN  39.164006  -86.584189   
327          NaN  43.457245  -76.501852   
328          NaN  40.641968  -73.976035   

                                          Geometry  
0         POINT (-86.532174816526 39.209402001487)  
1         POINT (-86.536225864906 39.172589612604)  
2         POINT (-86.492971346064 39.158675449588)  
3         POINT (-86.527261036202 39.143740768385)  
4         POINT (-86.545054219197 39.168929719659)  
..                                             ...  
324  POINT (-118.20836853061225 34.04003255102041)  
325  POINT (-122.67639845541511 45.50717851010966)  
326                 POINT (-86.5841895 39.1640057)  
327                 POINT (-76.5018515 43.4572455)  
328                 POINT (-73.9760349 40.6419679)  

[329 rows x 10 columns]

## Educational Institutions and Libraries Schools etc

In [49]:
edu_fac = pd.read_csv('/Users/mohammedpathariya/Downloads/educational_facilities_bloomington_categorized.csv')

In [50]:
print(", ".join([f'"{loc}"' for loc in edu_fac['Location']]))

"200 Daniels Way", "2088 Liberty Dr", "444 S Patterson Dr", "200 S Eagleson Ave", "1400 S Brenda Ave", "1655 E Bethel Ln", "201 N Rose Ave", "1835 S Highland Ave", "4000 E Moores Creek Rd", "303 E Kirkwood Ave", "1650 W Bloomfield Rd", "101 W Kirkwood Ave Suite 200", "900 S Park Square Dr", "1200 E 7th St", "3070 N Prow Rd", "2300 E 2nd St", "116 1/2 S College Ave Suite 11", "1315 East 10th Street", "315 E North Dr", "500 W 7th St", "952 S Kirby Rd", "217 W 6th St Suite 105", "1000 W 15th St", "304 W Howe St Suite B", "275 N Eagleson Ave", "2850 E Discovery Pkwy", "1111 N Russell Rd", "2300 S Endwright Rd", "Ellettsville, IN", "2230 N Martha St", "200 Daniels Way", "4001 E 3rd St Suite 1", "2320 N Smith Pike", "1320 E 10th St", "890 W Gordon Pike", "4609 IN-46", "312 E Dixie St", "800 E Kirkwood Ave", "705 W Coolidge Dr", "705 W Coolidge Dr", "4000 E Moores Creek Rd", "328 S Walnut St Ste 1", "2674 E 2nd St", "3230 S Walnut St", "349 S Walnut St", "1450 W Countryside Ln", "303 E Kirkwo

200 Daniels Way => Latitude: 40.24539291029812, Longitude: -74.27432916348606
2088 Liberty Dr => Latitude: 36.102531701248765, Longitude: -79.81710379955075
444 S Patterson Dr => Latitude: 35.33487173677323, Longitude: -97.47225164435535
200 S Eagleson Ave => Latitude: 39.16534885, Longitude: -86.51743911108935
1400 S Brenda Ave => Latitude: 39.16533, Longitude: -86.52639
1655 E Bethel Ln => Latitude: 39.21539553625489, Longitude: -86.51628592456056
201 N Rose Ave => Latitude: 39.16701535, Longitude: -86.51250049088785
1835 S Highland Ave => Latitude: 39.14446825, Longitude: -86.51677889819909
4000 E Moores Creek Rd => Latitude: 39.120071389033996, Longitude: -86.48411191823976
303 E Kirkwood Ave => Latitude: 39.16693765, Longitude: -86.530448225
1650 W Bloomfield Rd => Latitude: 42.95063622580645, Longitude: -77.53260848387097
101 W Kirkwood Ave Suite 200 => Latitude: 39.1662847, Longitude: -86.5342397
900 S Park Square Dr => Latitude: 39.156741, Longitude: -86.591861
1200 E 7th St => Latitude: 39.167913549999994, Longitude: -86.51898175
3070 N Prow Rd => Latitude: 39.197733297450604, Longitude: -86.55206746207621
2300 E 2nd St => Latitude: 40.59327355, Longitude: -73.9691260465438
116 1/2 S College Ave Suite 11 => Latitude: 39.1583322, Longitude: -86.5350232
1315 East 10th Street => Latitude: 40.61709245, Longitude: -73.96448375
315 E North Dr => Latitude: 39.14448801846578, Longitude: -86.52947895452469
500 W 7th St => Latitude: 42.099034, Longitude: -79.24856586938469
952 S Kirby Rd => Latitude: 39.15639506900914, Longitude: -86.61052547193955
217 W 6th St Suite 105 => Latitude: 39.1674803, Longitude: -86.5351782
1000 W 15th St => Latitude: 33.01878524999999, Longitude: -96.71599495792606
304 W Howe St Suite B => Latitude: 39.1624684, Longitude: -86.5364987
275 N Eagleson Ave => Latitude: 39.16837155, Longitude: -86.51691209250174
2850 E Discovery Pkwy => Latitude: 39.174901399999996, Longitude: -86.49732749433639
1111 N Russell Rd => Latitude: 39.1757974, Longitude: -86.4825937
2300 S Endwright Rd => Latitude: 39.14603169383584, Longitude: -86.59640384206081
Ellettsville, IN => Latitude: 39.2339348, Longitude: -86.6250008
2230 N Martha St => Latitude: 39.1867545, Longitude: -86.53134741710555
200 Daniels Way => Latitude: 40.24539291029812, Longitude: -74.27432916348606
4001 E 3rd St Suite 1 => Latitude: 14.453370041176868, Longitude: 120.98284321642807
2320 N Smith Pike => Latitude: 39.189154, Longitude: -86.583005
1320 E 10th St => Latitude: 39.17105145, Longitude: -86.51685115237282
890 W Gordon Pike => Latitude: 39.12219705, Longitude: -86.54270084904341
4609 IN-46 => Latitude: 16.0340137, Longitude: -16.505226200000003
312 E Dixie St => Latitude: 39.156307600000005, Longitude: -86.53065551011005
800 E Kirkwood Ave => Latitude: 41.565399, Longitude: -93.601757
705 W Coolidge Dr => Latitude: 39.14121002998908, Longitude: -86.5412674446561
705 W Coolidge Dr => Latitude: 39.14121002998908, Longitude: -86.5412674446561
4000 E Moores Creek Rd => Latitude: 39.120071389033996, Longitude: -86.48411191823976
328 S Walnut St Ste 1 => Latitude: 39.163879, Longitude: -86.5337375
2674 E 2nd St => Latitude: 39.1608406, Longitude: -86.4984163
3230 S Walnut St => Latitude: 37.63635214033444, Longitude: -97.35117151675402
349 S Walnut St => Latitude: 43.6052175, Longitude: -116.1846463
1450 W Countryside Ln => Latitude: 39.14128287170249, Longitude: -86.55321763859857
303 E Kirkwood Ave => Latitude: 39.16693765, Longitude: -86.530448225
7587 Rockport Rd => Latitude: 40.876821782462486, Longitude: -83.96127194322607
1150 N Union Ct => Latitude: 39.1745653, Longitude: -86.50884815782828
700 W Parrish Rd => Latitude: 39.188121550814216, Longitude: -86.53919936780892
1807 S Highland Ave => Latitude: 34.041892000000004, Longitude: -118.3458244
625 N Eagleson Ave => Latitude: 39.1723688, Longitude: -86.51595989451599
2224 E 3rd St => Latitude: 40.595845, Longitude: -73.96850300000001
501 N Morton St => Latitude: 39.170582, Longitude: -86.53621
2211 S High St => Latitude: 39.1384189, Longitude: -86.5061074
1025 E 7th St => Latitude: 39.1692206, Longitude: -86.52084144781067
530 W Church Ln => Latitude: 39.10741021849584, Longitude: -86.53971552051625
211 S Indiana Ave => Latitude: 39.1650891, Longitude: -86.52632642485594
300 W Clear Creek Dr => Latitude: 35.635504390107165, Longitude: -97.56410128827092
Ellettsville, IN => Latitude: 39.2339348, Longitude: -86.6250008
1500 E Hillside Dr => Latitude: 39.15046, Longitude: -86.51497
525 W 17th St => Latitude: 39.1787397, Longitude: -86.5393015
909 E 2nd St => Latitude: 39.1617495, Longitude: -86.52145479882076
3069 E Amy Ln => Latitude: 39.1693068, Longitude: -86.4968721
4423 E Trailridge Rd => Latitude: 35.60578181260297, Longitude: -82.53826117598238
1201 W That Rd => Latitude: 39.11452760107239, Longitude: -86.54548770288206
417 N Elm St => Latitude: 42.13961825, Longitude: -72.73441239648658
1320 E 10th St => Latitude: 39.17105145, Longitude: -86.51685115237282

In [51]:
# Dictionary mapping location to (latitude, longitude)
location_coords = {
    "200 Daniels Way": (40.24539291029812, -74.27432916348606),
    "2088 Liberty Dr": (36.102531701248765, -79.81710379955075),
    "444 S Patterson Dr": (35.33487173677323, -97.47225164435535),
    "200 S Eagleson Ave": (39.16534885, -86.51743911108935),
    "1400 S Brenda Ave": (39.16533, -86.52639),
    "1655 E Bethel Ln": (39.21539553625489, -86.51628592456056),
    "201 N Rose Ave": (39.16701535, -86.51250049088785),
    "1835 S Highland Ave": (39.14446825, -86.51677889819909),
    "4000 E Moores Creek Rd": (39.120071389033996, -86.48411191823976),
    "303 E Kirkwood Ave": (39.16693765, -86.530448225),
    "1650 W Bloomfield Rd": (42.95063622580645, -77.53260848387097),
    "101 W Kirkwood Ave Suite 200": (39.1662847, -86.5342397),
    "900 S Park Square Dr": (39.156741, -86.591861),
    "1200 E 7th St": (39.167913549999994, -86.51898175),
    "3070 N Prow Rd": (39.197733297450604, -86.55206746207621),
    "2300 E 2nd St": (40.59327355, -73.9691260465438),
    "116 1/2 S College Ave Suite 11": (39.1583322, -86.5350232),
    "1315 East 10th Street": (40.61709245, -73.96448375),
    "315 E North Dr": (39.14448801846578, -86.52947895452469),
    "500 W 7th St": (42.099034, -79.24856586938469),
    "952 S Kirby Rd": (39.15639506900914, -86.61052547193955),
    "217 W 6th St Suite 105": (39.1674803, -86.5351782),
    "1000 W 15th St": (33.01878524999999, -96.71599495792606),
    "304 W Howe St Suite B": (39.1624684, -86.5364987),
    "275 N Eagleson Ave": (39.16837155, -86.51691209250174),
    "2850 E Discovery Pkwy": (39.174901399999996, -86.49732749433639),
    "1111 N Russell Rd": (39.1757974, -86.4825937),
    "2300 S Endwright Rd": (39.14603169383584, -86.59640384206081),
    "Ellettsville, IN": (39.2339348, -86.6250008),
    "2230 N Martha St": (39.1867545, -86.53134741710555),
    "4001 E 3rd St Suite 1": (14.453370041176868, 120.98284321642807),
    "2320 N Smith Pike": (39.189154, -86.583005),
    "1320 E 10th St": (39.17105145, -86.51685115237282),
    "890 W Gordon Pike": (39.12219705, -86.54270084904341),
    "4609 IN-46": (16.0340137, -16.505226200000003),
    "312 E Dixie St": (39.156307600000005, -86.53065551011005),
    "800 E Kirkwood Ave": (41.565399, -93.601757),
    "705 W Coolidge Dr": (39.14121002998908, -86.5412674446561),
    "328 S Walnut St Ste 1": (39.163879, -86.5337375),
    "2674 E 2nd St": (39.1608406, -86.4984163),
    "3230 S Walnut St": (37.63635214033444, -97.35117151675402),
    "349 S Walnut St": (43.6052175, -116.1846463),
    "1450 W Countryside Ln": (39.14128287170249, -86.55321763859857),
    "7587 Rockport Rd": (40.876821782462486, -83.96127194322607),
    "1150 N Union Ct": (39.1745653, -86.50884815782828),
    "700 W Parrish Rd": (39.188121550814216, -86.53919936780892),
    "1807 S Highland Ave": (34.041892000000004, -118.3458244),
    "625 N Eagleson Ave": (39.1723688, -86.51595989451599),
    "2224 E 3rd St": (40.595845, -73.96850300000001),
    "501 N Morton St": (39.170582, -86.53621),
    "2211 S High St": (39.1384189, -86.5061074),
    "1025 E 7th St": (39.1692206, -86.52084144781067),
    "530 W Church Ln": (39.10741021849584, -86.53971552051625),
    "211 S Indiana Ave": (39.1650891, -86.52632642485594),
    "300 W Clear Creek Dr": (35.635504390107165, -97.56410128827092),
    "1500 E Hillside Dr": (39.15046, -86.51497),
    "525 W 17th St": (39.1787397, -86.5393015),
    "909 E 2nd St": (39.1617495, -86.52145479882076),
    "3069 E Amy Ln": (39.1693068, -86.4968721),
    "4423 E Trailridge Rd": (35.60578181260297, -82.53826117598238),
    "1201 W That Rd": (39.11452760107239, -86.54548770288206),
    "417 N Elm St": (42.13961825, -72.73441239648658),
}

# Update Latitude and Longitude columns in grocery_fac
edu_fac["Latitude"] = edu_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[0])
edu_fac["Longitude"] = edu_fac["Location"].map(lambda x: location_coords.get(x, (None, None))[1])

In [52]:
edu_fac["Geometry"] = edu_fac.apply(
    lambda row: f"POINT ({row['Longitude']} {row['Latitude']})" if pd.notnull(row['Latitude']) and pd.notnull(row['Longitude']) else None,
    axis=1
)

In [53]:
edu_fac

Facility Facility Group  \
0        Ivy Tech Community College Bloomington      Education   
1                              The Excel Center      Education   
2   The Academy of Science and Entrepreneurship      Education   
3                            Cook Music Library      Education   
4                   Templeton Elementary School      Education   
..                                          ...            ...   
63           Lisa's Bloomington English Academy      Education   
64                      Workshops By Thiagi Inc      Education   
65                 Lighthouse Christian Academy      Education   
66                        Longevity Bloomington      Education   
67                       Herman B Wells Library      Education   

              Type              Location  X Coordinate  Y Coordinate  \
0              NaN       200 Daniels Way           NaN           NaN   
1              NaN       2088 Liberty Dr           NaN           NaN   
2    Public School    444 S Patterson Dr           NaN           NaN   
3          Library    200 S Eagleson Ave           NaN           NaN   
4    Public School     1400 S Brenda Ave           NaN           NaN   
..             ...                   ...           ...           ...   
63   Public School         3069 E Amy Ln           NaN           NaN   
64             NaN  4423 E Trailridge Rd           NaN           NaN   
65  Private School        1201 W That Rd           NaN           NaN   
66             NaN          417 N Elm St           NaN           NaN   
67         Library        1320 E 10th St           NaN           NaN   

     Latitude  Longitude                                       Geometry  
0   40.245393 -74.274329   POINT (-74.27432916348606 40.24539291029812)  
1   36.102532 -79.817104  POINT (-79.81710379955075 36.102531701248765)  
2   35.334872 -97.472252   POINT (-97.47225164435535 35.33487173677323)  
3   39.165349 -86.517439         POINT (-86.51743911108935 39.16534885)  
4   39.165330 -86.526390                     POINT (-86.52639 39.16533)  
..        ...        ...                                            ...  
63  39.169307 -86.496872                 POINT (-86.4968721 39.1693068)  
64  35.605782 -82.538261   POINT (-82.53826117598238 35.60578181260297)  
65  39.114528 -86.545488   POINT (-86.54548770288206 39.11452760107239)  
66  42.139618 -72.734412         POINT (-72.73441239648658 42.13961825)  
67  39.171051 -86.516851         POINT (-86.51685115237282 39.17105145)  

[68 rows x 9 columns]

In [54]:
# Merge the two DataFrames vertically (stack one below the other)
merged_df_edu = pd.concat([merged_df_rest, edu_fac], ignore_index=True)

In [55]:
merged_df_edu.to_csv("city_facilities_and_extra.csv", index=False)

In [56]:
merged_df_edu

Place ID                              Facility    Facility Group  \
0       1561                     Ferguson Dog Park             Parks   
1       5069                        Innovation Lab      City Offices   
2       1795                         Latimer Woods             Parks   
3       5044  Frank Southern Ice Arena Parking Lot  Parking Facility   
4         95             Banneker Community Center             Parks   
..       ...                                   ...               ...   
392      NaN    Lisa's Bloomington English Academy         Education   
393      NaN               Workshops By Thiagi Inc         Education   
394      NaN          Lighthouse Christian Academy         Education   
395      NaN                 Longevity Bloomington         Education   
396      NaN                Herman B Wells Library         Education   

                     Type                       Location X Coordinate  \
0                Dog Park           4300 N Stone Mill RD      3108927   
1      Government Offices                627 N Morton ST      3107860   
2    Nature Park/Preserve     3200 E Buick Cadillac BLVD      3120156   
3                 Parking  N of Frank Southern Ice Arena      3110466   
4        Community Center                   930 W 7th ST      3105365   
..                    ...                            ...          ...   
392         Public School                  3069 E Amy Ln          NaN   
393                   NaN           4423 E Trailridge Rd          NaN   
394        Private School                 1201 W That Rd          NaN   
395                   NaN                   417 N Elm St          NaN   
396               Library                 1320 E 10th St          NaN   

    Y Coordinate   Latitude  Longitude  \
0        1443195  39.209444 -86.532102   
1        1429780  39.172582 -86.536221   
2        1424789  39.158671 -86.492991   
3        1419288  39.143733 -86.527257   
4        1428432  39.168922 -86.545049   
..           ...        ...        ...   
392          NaN  39.169307 -86.496872   
393          NaN  35.605782 -82.538261   
394          NaN  39.114528 -86.545488   
395          NaN  42.139618 -72.734412   
396          NaN  39.171051 -86.516851   

                                         Geometry  
0        POINT (-86.532174816526 39.209402001487)  
1        POINT (-86.536225864906 39.172589612604)  
2        POINT (-86.492971346064 39.158675449588)  
3        POINT (-86.527261036202 39.143740768385)  
4        POINT (-86.545054219197 39.168929719659)  
..                                            ...  
392                POINT (-86.4968721 39.1693068)  
393  POINT (-82.53826117598238 35.60578181260297)  
394  POINT (-86.54548770288206 39.11452760107239)  
395        POINT (-72.73441239648658 42.13961825)  
396        POINT (-86.51685115237282 39.17105145)  

[397 rows x 10 columns]